using Emulation;

namespace GameBoy.CPU;

/// <summary>
/// This class is a value object representing the internal state of the CPU, which the operational functions
/// on the CPU use to determine which steps to execute and to store values for and generated by those execs.
/// </summary>
public sealed class LR35902State : ICPUState
{
    //--------------------------------------------------------------------------------------------------//
    //                                           COUNTERS                                               //
    //--------------------------------------------------------------------------------------------------//
    public ushort PC         { get; internal set; } = 0x0100;   // Program Counter; Entry point
    public ushort SP         { get; internal set; } = 0xFFFE;   // Stack Pointer;   Top of HRAM
    public ulong  CycleCount { get; internal set; } = 0;        // Clock cycles (T-Cycles)
    public bool   Halted     { get; internal set; } = false;

    //--------------------------------------------------------------------------------------------------//
    //                                           REGISTERS                                              //
    //--------------------------------------------------------------------------------------------------//
    // The nibbled for registers on the CPU.
    // Together they form pairs which can be read out as such, the pairs are [ AF , BC, DE, HL ]
    public byte   A  { get; internal set; } = 0;
    public byte   B  { get; internal set; } = 0;
    public byte   C  { get; internal set; } = 0;
    public byte   D  { get; internal set; } = 0;
    public byte   E  { get; internal set; } = 0;
    public byte   F  { get; internal set; } = 0xB0;   // Convention (bits 5,7 set)
    public byte   H  { get; internal set; } = 0;
    public byte   L  { get; internal set; } = 0;
    
    // which are represented here in their full pairs
    // AF is used for the Accumulator and Flags:
    public ushort AF
    {
        get => (ushort)((A << 8) | F);
        set
        {
            A = (byte)(value >> 8);
            F = (byte)(value & 0xF0);   // lower nibble is always 0 on DMG CPU
        }
    }

    // While the other 3 are used as either general-purpose 16-bit registers,
    // though can also be split into 2 8-bit registers as needed by the program.
    // BC & DE are often used for data movement and counters.
    public ushort BC
    {
        get => (ushort)((B << 8) | C);
        set
        {
            B = (byte)(value >> 8);
            C = (byte)(value);
        }
    }

    public ushort DE
    {
        get => (ushort)((D << 8) | E);
        set
        {
            D = (byte)(value >> 8);
            E = (byte)(value);
        }
    }

    // While the HL register is frequently used as a memory pointer.
    public ushort HL
    {
        get => (ushort)((H << 8) | L);
        set
        {
            H = (byte)(value >> 8);
            L = (byte)(value);
        }
    }
    
    //--------------------------------------------------------------------------------------------------//
    //                                            FLAGS                                                 //
    //--------------------------------------------------------------------------------------------------//
    // Set of flags that can be set by the CPU  | The bitmasks for those flags.
    public bool FlagZ => (F & FlagZMask) != 0;   private const byte FlagZMask = 0x80;
    public bool FlagN => (F & FlagNMask) != 0;   private const byte FlagNMask = 0x40;
    public bool FlagH => (F & FlagHMask) != 0;   private const byte FlagHMask = 0x20;
    public bool FlagC => (F & FlagCMask) != 0;   private const byte FlagCMask = 0x10;
    
    //--------------------------------------------------------------------------------------------------//
    //                                          OPERATIONS                                              //
    //--------------------------------------------------------------------------------------------------//
    public void AddClockCycles(uint cycles)
    {
        CycleCount += cycles;
    }
    
    public void SetFlags(bool z, bool n, bool h, bool c)
    {
        F = 0x00;
        if (z) F |= FlagZMask;
        if (n) F |= FlagNMask;
        if (h) F |= FlagHMask;
        if (c) F |= FlagCMask;
    }
    
    public void SetFlagZ(bool set) => SetFlag(FlagZMask, set);
    public void SetFlagN(bool set) => SetFlag(FlagNMask, set);
    public void SetFlagH(bool set) => SetFlag(FlagHMask, set);
    public void SetFlagC(bool set) => SetFlag(FlagCMask, set);
    
    private void SetFlag(byte mask, bool set)
    {
        if (set) F |= mask;
        else     F &= (byte)~mask;

        F &= 0xF0;
    }
    
    /// <summary> Reset the CPU State, this is usually done when a ROM is loaded </summary>
    public void Reset()
    {
        CycleCount = 0; Halted = false;
        
        PC = 0x0100; SP = 0xFFFE;

        A = 0x00; F = 0xB0;
        B = 0x00; C = 0x00;
        D = 0x00; E = 0x00;
        H = 0x00; L = 0x00;
    }

}

/// <summary>
/// This class houses the executional logic of the CPU, which uses the state to determine what to do next
/// and to store values for and generated by those executions.
/// </summary>
public sealed class LR35902 : ICPU
{
    // 1 DMG Machine Cycle equates to 4 clock cycles (or T-cycles) on the CPU.
    private const int MachineCycle = 4;
    
    private readonly LR35902State _state = new();
    private          Bus?         _bus;
    
    public ICPUState State => _state;
    public void AttachBus(Bus bus) => _bus = bus;

    /// <summary> Reset logic for the CPU. </summary>
    public void Reset()
    {
        _state.Reset();
        _bus = null;
    }

    /// <summary> Step the next instruction and executes the opcode found at that instruction. </summary>
    public void StepInstruction()
    {
        if (_bus is null || _state.Halted)
            return;

        // Read the Next opcode from the BUS (loaded from the cart)
        byte opcode = _bus.ReadByte(_state.PC);
        
        // Step the Program Counter then execute the opcode
        _state.PC++; 
        _state.AddClockCycles(MachineCycle); // fetch uses a machine cycle.

        switch (opcode)
        {
            case 0x00: return;  // NOP

            case 0x3E:          // LD A,d8
            {
                byte value = _bus.ReadByte(_state.PC);
                
                _state.PC++;
                _state.A = value;
                
                _state.AddClockCycles(MachineCycle); // total 8
                return;
            }

            case 0x18:          // JR r8
            {
                sbyte offset = unchecked((sbyte)(_bus.ReadByte(_state.PC)));
                
                _state.PC++;
                _state.PC = (ushort)(_state.PC + offset);
                
                _state.AddClockCycles(MachineCycle * 2); // total 12
                return;
            }

            case 0xC3:          // JP a16          
            {
                _state.PC = ReadNextWord();
                
                _state.AddClockCycles(MachineCycle * 3); // total 16
                return;
            }

            case 0x31:          // LD SP,d16
            {
                _state.SP = ReadNextWord();
                
                _state.AddClockCycles(MachineCycle * 2); // total 12
                return;
            }
            
            case 0xEA:          // LD (a16),A
            {
                _bus.WriteByte(ReadNextWord(), _state.A);

                _state.AddClockCycles(MachineCycle * 3); // total 16
                return;
            }

            case 0xFA:          // LD (a16),A
            {
                _state.A = _bus.ReadByte(ReadNextWord());

                _state.AddClockCycles(MachineCycle * 3); // total 16
                return;
            }

            case 0xCD:          // CALL a16
            {
                ushort target = ReadNextWord();
                
                PushWord(_state.PC);
                _state.PC = target;
                
                _state.AddClockCycles(MachineCycle * 5); // total 24
                return;
            }

            case 0xC9:          // RET
            {
                _state.PC = PopWord();
                
                _state.AddClockCycles(MachineCycle * 3); // total 16
                return;
            }
            
            default: throw new NotSupportedException($"Opcode {opcode} not supported");
        }
    }

    /// <summary> Reads the next word from the instruction stream; advances the PC. </summary>
    private ushort ReadNextWord()
    {
        if (_bus is null) return 0;
        
        byte lo = _bus.ReadByte(_state.PC); _state.PC++;
        byte hi = _bus.ReadByte(_state.PC); _state.PC++;
        
        return (ushort)((hi << 8) | lo);
    }

    /// <summary> Push a word onto the stack. </summary>
    private void PushWord(ushort value)
    {
        if (_bus is null) return;

        _state.SP--; _bus.WriteByte(_state.SP, (byte)(value >> 8));   // high byte
        _state.SP--; _bus.WriteByte(_state.SP, (byte)(value & 0xFF)); // low byte
    }

    /// <summary> Pop a word from the stack. </summary>
    private ushort PopWord()
    {
        if (_bus is null) return 0;
        
        byte lo = _bus.ReadByte(_state.SP); _state.SP++;
        byte hi = _bus.ReadByte(_state.SP); _state.SP++;
        
        return (ushort)((hi << 8) | lo);
    }
}