using Emulation;

namespace GameBoy.CPU;

/// <summary>
/// This class houses the executional logic of the CPU, which uses the state to determine what to do next
/// and to store values for and generated by those executions.
/// </summary>
public sealed class LR35902 : ICPU
{
    //--------------------------------------------------------------------------------------------------//
    //                                          ATTRIBUTES                                              //
    //--------------------------------------------------------------------------------------------------//
    // 1 DMG Machine Cycle equates to 4 clock cycles (or T-cycles) on the CPU.
    private const uint MachineCycle = 4;
    
    private readonly LR35902State _state = new();
    private          Bus?         _bus;
    
    public ICPUState State => _state;
    
    //--------------------------------------------------------------------------------------------------//
    //                                          FUNCTIONS                                               //
    //--------------------------------------------------------------------------------------------------//
    /// <summary> Attach a BUS, usually loaded from a ROM. </summary>
    public void AttachBus(Bus bus) => _bus = bus;

    /// <summary> Reset logic for the CPU. </summary>
    public void Reset()
    {
        _state.Reset();
        _bus = null;
    }

    //--------------------------------------------------------------------------------------------------//
    //                                            OPCODES                                               //
    //--------------------------------------------------------------------------------------------------//
    /// <summary> Step the next instruction and executes the opcode found at that instruction. </summary>
    public void StepInstruction()
    {
        if (_bus is null || _state.Halted || _state.Stopped)
            return;

        // Read the Next opcode from the BUS (loaded from the cart)
        byte opcode = _bus.ReadByte(_state.PC);
        
        // Step the Program Counter then execute the opcode
        _state.PC++; 
        _state.AddClockCycles(MachineCycle); // fetch uses a machine cycle.

        switch (opcode)
        {
            //----------    MISC    ----------//
            case 0x00: return;  // NOP

            //---------- CTRL ----------//
            //--- STOP
            case 0x10:
            {
                _state.Stop();  // Enter stopped state until external wake event.
                
                // Timing:  (4 total cycles)
                //  - opcode fetch: 4 cycles.
                //  - STOP is a 1-byte instruction in this simplified model.
                return;
            }

            //--- HALT
            case 0x76:
            {
                _state.Halt();  // Enter halted state until interrupt-related wake event.
                
                // Timing:  (4 total cycles)
                //  - opcode fetch: 4 cycles.
                //  - STOP is a 1-byte instruction in this simplified model.
                return;
            }

            //----------    LD16    ----------//
            //--- LD rr,d16
            case 0x01: case 0x11: case 0x21: case 0x31:
            {
                // Read the next 16-bits from operand; advances PC past both bytes.
                ushort val = ReadNextWord();

                // bits 5-4 of these opcodes encode which 16-bit register pair to load:
                // 00=BC, 01=DE, 10=HL, 11=SP
                switch ((opcode >> 4) & 0x03)
                {
                    case 0x00: _state.BC = val; break;
                    case 0x01: _state.DE = val; break;
                    case 0x02: _state.HL = val; break;
                    case 0x03: _state.SP = val; break;
                }
                
                // Timing:  (12 total cycles)
                //  - opcode fetch: 4 cycles.
                //  - LD rr,d16:    8 cycles.
                _state.AddClockCycles(MachineCycle * 2);
                return;
            }
            //----------    ALU16    ----------//
            //--- INC rr
            case 0x03: case 0x13: case 0x23: case 0x33:
            {
                // Bits 5-4 encode the 16-bit register target:
                // 00=BC, 01=DE, 10=HL, 11=SP.
                switch ((opcode >> 4) & 0x03)
                {
                    case 0x00: _state.BC++; break;
                    case 0x01: _state.DE++; break;
                    case 0x02: _state.HL++; break;
                    case 0x03: _state.SP++; break;
                }
                // INC rr does not affect flags on LR35902.
                
                // Timing:  (8 total cycles)
                //  - opcode fetch: 4 cycles.
                //  - INC rr:       4 cycles.
                _state.AddClockCycles(MachineCycle);
                return;
            }
            
            //--- DEC rr
            case 0x0B: case 0x1B: case 0x2B: case 0x3B:
            {
                // Bits 5-4 encode the 16-bit register target:
                // 00=BC, 01=DE, 10=HL, 11=SP.
                switch ((opcode >> 4) & 0x03)
                {
                    case 0x00: _state.BC--; break;
                    case 0x01: _state.DE--; break;
                    case 0x02: _state.HL--; break;
                    case 0x03: _state.SP--; break;
                }
                // DEC rr does not affect flags on LR35902.

                // Timing:  (8 total cycles)
                //  - opcode fetch: 4 cycles.
                //  - INC rr:       4 cycles.
                _state.AddClockCycles(MachineCycle);
                return;
            }
            
            //--- ADD HL,rr
            case 0x09: case 0x19: case 0x29: case 0x39:
            {
                // Bits 5-4 encode the 16-bit source register pair:
                // 00=BC, 01=DE, 10=HL, 11=SP.
                ushort rr = ((opcode >> 4) & 0x03) switch
                {
                    0x00 => _state.BC,
                    0x01 => _state.DE,
                    0x02 => _state.HL,
                    _    => _state.SP
                };
                
                ushort hl  = _state.HL;     // Keep old HL for half-carry/carry checks.
                int    sum = hl + rr;       // Then add RR to HL.
                _state.HL  = (ushort)sum;   // Write back the result.
                
                SetFlagsZNHC(
                    z: _state.FlagZ,                                // unchanged.
                    n: false,                                       // 0.
                    h: ((hl & 0x0FFF) + (rr & 0x0FFF)) > 0x0FFF,    // carry from bit 11
                    c: sum > 0xFFFF);                               // carry from bit 15
                
                // Timing:  (8 total cycles)
                //  - opcode fetch: 4 cycles.
                //  - ADD HL,rr:    4 cycles.
                _state.AddClockCycles(MachineCycle);
                return;
            }
            
            //--- ADD SP,e8
            case 0xE8:
            {
                byte e8   = ReadNextByte();     // Read signed 8-bit immediate operand.
                _state.SP = AddSignedToSP(e8);  // Add signed immediate to SP.
                
                // Helper applies LR35902 flag behavior for this instruction:
                // Z=0, N=0, H/C from low-byte carry behavior.
                
                // Timing:  (16 total cycles)
                //  - opcode fetch: 4 cycles.
                //  - ADD SP,e8:    12 cycles.
                _state.AddClockCycles(MachineCycle * 3);
                return;
            }
            
            //--- LD HL,SP+e8
            case 0xF8:
            {
                
                byte e8   = ReadNextByte();     // Read signed 8-bit immediate operand.
                _state.HL = AddSignedToSP(e8);  // Compute SP + signed immediate and store into HL.
                
                // Uses same flag behavior as ADD SP,e8 via shared helper.

                // Timing:  (16 total cycles)
                //  - opcode fetch: 4 cycles.
                //  - ADD SP,e8:    12 cycles.
                _state.AddClockCycles(MachineCycle * 2); // total 12
                return;
            }
            

            //----------    LD8    ----------//
            case 0x06: case 0x0E: case 0x16: case 0x1E: 
            case 0x26: case 0x2E: case 0x36: case 0x3E:
            {
                // Read the next 8-bits from bus; advances PC past that byte.
                byte val = ReadNextByte();
                
                // Bits 5-3 encode the destination register index:
                // 0=B, 1=C, 2=D, 3=E, 4=H, 5=L, 6=(HL), 7=A.
                int dest = (opcode >> 3) & 0x07;
                
                WriteReg8(dest, val);
                
                
                // Timing:  (8/12 total cycles)
                //  - opcode fetch: 4 cycles.
                //  - LD r,d8:      4 cycles.
                //  - LD (HL),d8:   8 cycles.
                _state.AddClockCycles((dest == 6) ? MachineCycle * 2 : MachineCycle);
                return;
            }
            
            //----------    ALU8    ----------//
            //--- INC r/(HL)
            case 0x04: case 0x0C: case 0x14: case 0x1C:
            case 0x24: case 0x2C: case 0x34: case 0x3C:
            {
                // Bits 5-3 of this opcode select the target register index:
                // 0=B, 1=C, 2=D, 3=E, 4=H, 5=L, 6=(HL), 7=A.
                int target = (opcode >> 3) & 0x07;
                
                byte old    = ReadReg8(target); // Read current 8-bit value from the selected source.
                byte result = (byte)(old + 1);  // Perform 8-bit increment with wraparound (0xFF -> 0x00).
                
                WriteReg8(target, result);      // Write back to the same register
                
                bool carry  = _state.FlagC;     // INC affects Z, N, H and leaves C unchanged. Preserve carry.
                SetFlagsZNHC(
                    z: result == 0,             // Z: Set if result is 0.
                    n: false,                   // N: Reset for increment.
                    h: (old & 0x0F) == 0x0F,    // H: Set when low nibble overflowed
                    c: carry);                  // C: Unchanged
                
                // Timing:  (4/12 total cycles)
                //  - opcode fetch: 4 cycles.
                //  - INC r,r8:     0 cycles
                //  - INC r,HL:     8 cycles.
                if (target == 6)
                    _state.AddClockCycles(MachineCycle * 2);
                
                return;
            }
            
            //--- DEC r/(HL)
            case 0x05: case 0x0D: case 0x15: case 0x1D:
            case 0x25: case 0x2D: case 0x35: case 0x3D:
            {
                // Bits 5-3 of this opcode select the target register index:
                // 0=B, 1=C, 2=D, 3=E, 4=H, 5=L, 6=(HL), 7=A.
                int target = (opcode >> 3) & 0x07;
                
                byte old    = ReadReg8(target); // Read current 8-bit value from the selected source.
                byte result = (byte)(old - 1);  // Perform 8-bit increment with wraparound (0x00 -> 0xFF).
                
                WriteReg8(target, result);      // Write back to the same register
                
                bool carry  = _state.FlagC;     // INC affects Z, N, H and leaves C unchanged. Preserve carry.
                SetFlagsZNHC(
                    z: result == 0,             // Z: Set if result is 0.
                    n: true,                    // N: Set for dencrement.
                    h: (old & 0x0F) == 0X00,    // H: Set when low nibble overflowed
                    c: carry);                  // C: Unchanged

                // Timing:  (8 total cycles)
                //  - opcode fetch: 4 cycles.
                //  - HL form only: 8 cycles.
                if (target == 6)
                    _state.AddClockCycles(MachineCycle * 2);
                
                return;
            }

            //--- DAA (Decimal Adjust After)
            case 0x27:
            {
                // DAA adjusts A to a valid BCD result after ADD/ADC or SUB/SBC,
                // using the current N/H/C flags to determine which corrections to apply.
                byte a = _state.A; byte correction = 0;
                bool n = _state.FlagN; bool h = _state.FlagH; bool c = _state.FlagC;

                if (!n) // Addition correction
                {
                    if (h || (a & 0x0F) > 0x09) // If half-carry set or low nibble > 9
                        correction |= 0x06;     // add 0x06.
                    
                    if (c || a > 0x99)          //  If carry set or A > 0x99
                    {
                        correction |= 0x60;     // add 0x60 and set carry.
                        c = true;
                    }

                    a = (byte)(a + correction);
                }
                else    // Subtraction correction
                {
                    if (h) correction |= 0x06;  // If half-carry set, subtract 0x06.
                    if (c) correction |= 0x60;  // If carry set, subtract 0x60.
                    
                    a = (byte)(a - correction);
                }

                _state.A = a;
                SetFlagsZNHC(
                    z: _state.A == 0,   // set if adjusted A is 0.
                    n: n,               // unchanged.
                    h: false,           // reset.
                    c: c);              // unchanged.
                
                // Timing:  (4 total cycles)
                //  - opcode fetch: 4 cycles.
                return;
            }
            
            //--- CPL (Complement Accumulator)
            case 0x2F:
            {
                _state.A = (byte)~_state.A;  // Invert all bits in A (1's complement).
                
                SetFlagsZNHC(
                    z: _state.FlagZ,    // unchanged.
                    n: true,            // set.
                    h: true,            // set.
                    c: _state.FlagC);   // unchanged.
                
                // Timing:  (4 total cycles)
                //  - opcode fetch: 4 cycles.
                return;
            }
            
            //--- SCF (Set Carry Flag)
            case 0x37:
            {
                SetFlagsZNHC(
                    z: _state.FlagZ,    // unchanged.
                    n: false,           // reset.
                    h: false,           // reset.
                    c: true);           // set.
                
                // Timing:  (4 total cycles)
                //  - opcode fetch: 4 cycles.
                return;
            }

            //----------    ROTATE    ----------//
            case 0x07:          // RLCA
            {
                bool carry = (_state.A & 0x80) != 0;                         // Capture bit 7, this becomes carry & new bit 0.
                _state.A   = (byte)((_state.A << 1) | (carry ? 1 : 0));      // Rotate A left circular.
                
                // RLCA flags on LR35902: Z=0, N=0, H=0, C=old bit7.
                SetFlagsZNHC(z: false, n: false, h: false, c: carry);
                
                // Timing:  (4 total cycles)
                //  - opcode fetch: 4 cycles.
                return;
            }
            case 0x0F:          // RRCA
            {
                bool carry = (_state.A & 0x01) != 0;                          // Capture bit 0, this becomes carry & new bit 7.
                _state.A   = (byte)((_state.A >> 1) | (carry ? 0x80 : 0x00)); // Rotate A right circular.
                
                // RRCA flags on LR35902: Z=0, N=0, H=0, C=old bit7.
                SetFlagsZNHC(z: false, n: false, h: false, c: carry);

                // Timing:  (4 total cycles)
                //  - opcode fetch: 4 cycles.
                return;
            }

            case 0x17:          // RLA
            {
                bool oldCarry = _state.FlagC;                            // RLA Rotates left through carry:
                bool carryOut = (_state.A & 0x80) != 0;                  // old carry -> bit 0, old bit 7 -> new carry.
                
                _state.A = (byte)((_state.A << 1) | (oldCarry ? 1 : 0));
                
                // RLA flags on LR35902: Z=0, N=0, H=0, C=old bit7.
                SetFlagsZNHC(z: false, n: false, h: false, c: carryOut);
                
                // Timing:  (4 total cycles)
                //  - opcode fetch: 4 cycles.
                return;
            }
            case 0x1F:          // RRA
            {
                bool oldCarry = _state.FlagC;                            // RLA Rotates right through carry:
                bool carryOut = (_state.A & 0x01) != 0;                  // old carry -> bit 0, old bit 7 -> new carry.
                
                _state.A = (byte)((_state.A >> 1) | (oldCarry ? 0x80 : 0x00));
                
                // RLA flags on LR35902: Z=0, N=0, H=0, C=old bit7.
                SetFlagsZNHC(z: false, n: false, h: false, c: carryOut);
                
                // Timing:  (4 total cycles)
                //  - opcode fetch: 4 cycles.
                return;
            }
            
            //----------    FLOW    ----------//
            case 0x18:          // JR r8
            {
                sbyte offset = unchecked((sbyte)ReadNextByte());
                _state.PC = (ushort)(_state.PC + offset);
                
                _state.AddClockCycles(MachineCycle * 2); // total 12
                return;
            }
            
            case 0x20:          // JR NZ,e8
            case 0x28:          // JR Z,e8
            case 0x30:          // JR NC,e8
            case 0x38:          // JR C,e8
            {
                sbyte offset = unchecked((sbyte)ReadNextByte());
                ConditionCode cond = (ConditionCode)((opcode >> 3) & 0x03);

                if (CheckCond(cond))
                {
                    _state.PC = (ushort)(_state.PC + offset);
                    _state.AddClockCycles(MachineCycle * 2); // taken: +8 (total 12)
                }
                else
                    _state.AddClockCycles(MachineCycle);     // not taken: +4 (total 8)

                return;
            }
            
            case 0xC3:          // JP a16
            {
                _state.PC = ReadNextWord();
                
                _state.AddClockCycles(MachineCycle * 3); // total 16
                return;
            }

            case 0xC9:          // RET
            {
                _state.PC = PopWord();
                
                _state.AddClockCycles(MachineCycle * 3); // total 16
                return;
            }

            case 0xCD:          // CALL a16
            {
                ushort target = ReadNextWord();
                
                PushWord(_state.PC);
                _state.PC = target;
                
                _state.AddClockCycles(MachineCycle * 5); // total 24
                return;
            }

            //----------    MEM    ----------//
            //--- LD (BC/DE),A
            case 0x02: case 0x12:
            {
                // Select the destination address from BC/DE based on opcode.
                ushort dest = (opcode == 0x02 ? _state.BC : _state.DE);
                
                // Store accumulator into memory at the destination address.
                _bus.WriteByte(dest, _state.A);
                
                // Timing:  (8 total)
                //  - opcode fetch: 4 cycles.
                //  - LD (BC/DE),A: 4 cycles.
                _state.AddClockCycles(MachineCycle);
                return;
            }
            
            //--- LD (BC/DE),A
            case 0x0A: case 0x1A:
            {
                // Select the source address from BC/DE based on opcode.
                ushort src = (opcode == 0x0A ? _state.BC : _state.DE);
                
                // Load accumulator from memory at the source address.
                _state.A = _bus.ReadByte(src);
                
                // Timing:  (8 total)
                //  - opcode fetch: 4 cycles.
                //  - LD A,(BC/DE): 4 cycles.
                _state.AddClockCycles(MachineCycle);
                return;
            }
            
            // --- LD (HL+/-),A
            case 0x22: case 0x32:
            {
                // Write to HL then increment or decrement based on opcode.
                WriteAtHL(_state.A, 
                    opcode == 0x22 ? HLStep.Increment : HLStep.Decrement);

                // Timing:  (8 total)
                //  - opcode fetch: 4 cycles.
                //  - LD (HL+/-),A: 4 cycles.
                _state.AddClockCycles(MachineCycle);
                return;
            }

            // --- LD A,(HL+/-)
            case 0x2A: case 0x3A:
            {
                // Read from HL then increment or decrement based on opcode.
                _state.A = ReadAtHL(
                    opcode == 0x2A ? HLStep.Increment : HLStep.Decrement);

                // Timing:  (8 total)
                //  - opcode fetch: 4 cycles.
                //  - LD (HL+/-),A: 4 cycles.
                _state.AddClockCycles(MachineCycle);
                return;
            }
            
            case 0x77:          // LD (HL),A
            {
                WriteAtHL(_state.A);

                _state.AddClockCycles(MachineCycle); // total 8
                return;
            }
            
            case 0x7E:          // LD A,(HL)
            {
                _state.A = ReadAtHL();
                
                _state.AddClockCycles(MachineCycle); // total 8
                return;
            }

            //--- LD (a16),SP
            case 0x08:
            {
                // Read the destination address from the immediate operand.
                ushort dest = ReadNextWord();

                // Store SP as little-endian at [a16] and [a16+1].
                _bus.WriteByte(dest, (byte)(_state.SP & 0x00FF));
                _bus.WriteByte((ushort)(dest + 1), (byte)(_state.SP >> 8));

                // Timing: 20 total cycles.
                // - opcode fetch already consumed 4 cycles.
                // - LD (a16),SP consumes 16 more cycles.
                _state.AddClockCycles(MachineCycle * 4);
                return;
            }
            
            case 0xEA:          // LD (a16),A
            {
                _bus.WriteByte(ReadNextWord(), _state.A);

                _state.AddClockCycles(MachineCycle * 3); // total 16
                return;
            }

            case 0xFA:          // LD A,(a16)
            {
                _state.A = _bus.ReadByte(ReadNextWord());

                _state.AddClockCycles(MachineCycle * 3); // total 16
                return;
            }
            
            default: throw new NotSupportedException($"Opcode {opcode} not supported");
        }
    }
    
    //--------------------------------------------------------------------------------------------------//
    //                                            HELPERS                                               //
    //--------------------------------------------------------------------------------------------------//
    /// <summary> Reads the next word from the instruction stream; advances the PC. </summary>
    private byte ReadNextByte()
    {
        if (_bus is null) return 0;

        byte value = _bus.ReadByte(_state.PC);
        _state.PC++;

        return value;
    }

    /// <summary> Reads the next word from the instruction stream; advances the PC. </summary>
    private ushort ReadNextWord()
    {
        byte lo = ReadNextByte();
        byte hi = ReadNextByte();
        
        return (ushort)((hi << 8) | lo);
    }

    /// <summary> Push a word onto the stack. </summary>
    private void PushWord(ushort value)
    {
        if (_bus is null) return;

        _state.SP--; _bus.WriteByte(_state.SP, (byte)(value >> 8));   // high byte
        _state.SP--; _bus.WriteByte(_state.SP, (byte)(value & 0xFF)); // low byte
    }

    /// <summary> Pop a word from the stack. </summary>
    private ushort PopWord()
    {
        if (_bus is null) return 0;
        
        byte lo = _bus.ReadByte(_state.SP); _state.SP++;
        byte hi = _bus.ReadByte(_state.SP); _state.SP++;
        
        return (ushort)((hi << 8) | lo);
    }

    /// <summary> How HL should be adjusted after a memory access. </summary>
    private enum HLStep { None, Increment, Decrement }

    /// <summary> Read a byte from the address in HL, optionally adjusting HL after reading. </summary>
    private byte ReadAtHL(HLStep step = HLStep.None)
    {
        if (_bus is null) return 0;

        byte value = _bus.ReadByte(_state.HL);

        if (step == HLStep.Increment) _state.HL++;
        if (step == HLStep.Decrement) _state.HL--;
        
        return value;
    }
    
    /// <summary> Write a byte to the address in HL, optionally adjusting HL after writing. </summary>
    private void WriteAtHL(byte value, HLStep step = HLStep.None)
    {
        if (_bus is null) return;

        _bus.WriteByte(_state.HL, value);

        if (step == HLStep.Increment) _state.HL++;
        if (step == HLStep.Decrement) _state.HL--;
    }
    
    /// <summary> Read an 8-bit register by LR35902 register index (B,C,D,E,H,L,(HL),A). </summary>
    private byte ReadReg8(int reg)
    {
        return reg switch
        {
            0 => _state.B,
            1 => _state.C,
            2 => _state.D,
            3 => _state.E,
            4 => _state.H,
            5 => _state.L,
            6 => ReadAtHL(),
            7 => _state.A,
            _ => throw new ArgumentOutOfRangeException(nameof(reg), reg, "register index must be 0..7")
        };
    }
    
    /// <summary> Write an 8-bit register by LR35902 register index (B,C,D,E,H,L,(HL),A). </summary>
    private void WriteReg8(int reg, byte value)
    {
        switch (reg)
        {
            case 0: _state.B = value; break;
            case 1: _state.C = value; break;
            case 2: _state.D = value; break;
            case 3: _state.E = value; break;
            case 4: _state.H = value; break;
            case 5: _state.L = value; break;
            case 6: WriteAtHL(value); break;
            case 7: _state.A = value; break;
            default:
                throw new ArgumentOutOfRangeException(nameof(reg), reg, "register index must be 0..7");
        }
    }
    
    /// <summary> Set CPU flags in Z/N/H/C order. </summary>
    private void SetFlagsZNHC(bool z, bool n, bool h, bool c)
    {
        _state.SetFlags(z, n, h, c);
    }
    
    /// <summary>
    /// Adds signed 8-bit immediate to SP and updates flags per LR35902 rules.
    /// Used by: ADD SP,e8 and LD HL,SP+e8.
    /// </summary>
    private ushort AddSignedToSP(byte e8)
    {
        ushort sp = _state.SP;
        int    signed = unchecked((sbyte)e8);
        ushort result = (ushort)(sp + signed);

        // GB rule: Z=0, N=0, H/C from low-byte addition using unsigned e8.
        bool h = ((sp & 0x0F) + (e8 & 0x0F)) > 0x0F;
        bool c = ((sp & 0xFF) + e8) > 0xFF;

        SetFlagsZNHC(z: false, n: false, h: h, c: c);
        return result;
    }
    
    /// <summary> Makes condition code usage clearer than raw ints </summary>
    private enum ConditionCode { NZ = 0, Z  = 1, NC = 2, C  = 3 }
    
    /// <summary> Evaluate NZ/Z/NC/C condition code used by JR/JP/CALL/RET conditional forms. </summary>
    private bool CheckCond(ConditionCode cond)
    {
        return cond switch
        {
            ConditionCode.NZ => !_state.FlagZ,
            ConditionCode.Z  =>  _state.FlagZ,
            ConditionCode.NC => !_state.FlagC,
            ConditionCode.C  =>  _state.FlagC,
            _ => throw new ArgumentOutOfRangeException(nameof(cond), cond, null)
        };
    }
}
