using Emulation;

namespace GameBoy.CPU;

/// <summary>
/// This class houses the executional logic of the CPU, which uses the state to determine what to do next
/// and to store values for and generated by those executions.
/// </summary>
public sealed partial class LR35902 : ICPU
{
    //--------------------------------------------------------------------------------------------------//
    //                                          ATTRIBUTES                                              //
    //--------------------------------------------------------------------------------------------------//
    // 1 DMG Machine Cycle equates to 4 clock cycles (or T-cycles) on the CPU.
    private const uint MachineCycle = 4;
    
    // Interrupt codes for the CPU
    private const ushort InterruptFlagAddress   = 0xFF0F;
    private const ushort InterruptEnableAddress = 0xFFFF;
    private const byte   InterruptVBlank        = 0x01;
    private const byte   InterruptStat          = 0x02;
    private const byte   InterruptTimer         = 0x04;
    private const byte   InterruptSerial        = 0x08;
    private const byte   InterruptJoypad        = 0x10;
    
    private readonly LR35902State _state = new();
    private          Bus?         _bus;
    private          bool         _interruptEnabledPendingStateSnapshot;
    
    public ICPUState State => _state;
    
    //--------------------------------------------------------------------------------------------------//
    //                                          FUNCTIONS                                               //
    //--------------------------------------------------------------------------------------------------//
    /// <summary> Attach a BUS, usually loaded from a ROM. </summary>
    public void AttachBus(Bus bus) => _bus = bus;

    /// <summary> Reset logic for the CPU. </summary>
    public void Reset()
    {
        _state.Reset();
        _bus = null;
    }

    //--------------------------------------------------------------------------------------------------//
    //                                            OPCODES                                               //
    //--------------------------------------------------------------------------------------------------//
    /// <summary>
    /// Step the next instruction then execute the opcode at that location
    /// and return the number of clock cycles used in this step.
    /// </summary>
    public uint StepInstruction()
    {
        // Either no ROM is loaded or the execution is stopped, simply return.
        if (_bus is null || _state.Stopped)
            return 0;
        
        // Note the number of cycles used before execution the instruction.
        ulong cycleCountBeforeStep = _state.CycleCount;
        
        // Interrupt wake/service is checked before normal opcode execution.
        // HALT wakes when any enabled interrupt is pending. Interrupt servicing itself only occurs when IME is enabled.
        if (HandleInterrupts())
            return (uint)(_state.CycleCount - cycleCountBeforeStep);
        
        // Don't step if state is halted, but use a machine cycle waiting.
        if (_state.Halted)
        {
            _state.AddClockCycles(MachineCycle);
            return MachineCycle;
        }
        
        // EI on previous instruction is applied only after the current instruction completes.
        // Create a snapshot of the current InterruptEnabledPending state.
        _interruptEnabledPendingStateSnapshot = _state.InterruptEnabledPending;

        // Read the Next opcode from the BUS (loaded from the cart)
        byte opcode = _bus.ReadByte(_state.PC);
        
        _state.StepPC();                     // Step the Program Counter then execute the opcode
        _state.AddClockCycles(MachineCycle); // fetch uses a machine cycle.

        switch (opcode)
        {
            //------------------------    CONTROL    ------------------------//
            case 0x00: NOP();  break;                          //--- NOP
            case 0x10: STOP(); break;                          //--- STOP
            case 0x76: HALT(); break;                          //--- HALT
            case 0xF3: DI();   break;                          //--- DI (Disable Interrupts)
            case 0xFB: EI();   break;                          //--- EI (Enable Interrupts)
            
            //------------------------     FLOW    ------------------------//
            case 0x18: JR_r8(opcode); break;                   //--- JR r8
            
            case 0x20:/*JR NZ,e8*/ case 0x28:/*JR Z,e8*/       //--- JR N',e8
            case 0x30:/*JR NC,e8*/ case 0x38:/*JR C,e8*/
                JR_N_e8(opcode); break;
            
            case 0xC3: JP_a16(); break;                        //--- JP a16
            
            case 0xC2:/*NZ,a16*/ case 0xCA:/*Z,a16*/           //--- JP cc,a16
            case 0xD2:/*NC,a16*/ case 0xDA:/*C,a16*/
                JP_cc_a16(opcode); break;
            
            case 0xE9: JP_HL(); break;                         //--- JP HL
            
            case 0xC0:/*NZ,a16*/ case 0xC8:/*Z,a16*/           //--- RET cc
            case 0xD0:/*NC,a16*/ case 0xD8:/*C,a16*/
                RET_cc(opcode); break;
            
            case 0xC9: RET();  break;                          //--- RET
            case 0xD9: RETI(); break;                          //--- RETI (Return from Interrupt)
            
            case 0xC7: case 0xCF: case 0xD7: case 0xDF:        //--- RST vec (Call to a fixed vector)
            case 0xE7: case 0xEF: case 0xF7: case 0xFF:
                RST_vec(opcode); break;
            
            case 0xC4:/*NZ,a16*/ case 0xCC:/*Z,a16*/           //--- CALL cc,a16
            case 0xD4:/*NC,a16*/ case 0xDC:/*C,a16*/
                CALL_cc_a16(opcode); break;
            
            case 0xCD: CALL_a16(); break;                      //--- CALL a16
            
            //------------------------   CB_PREFIX   ------------------------//
            case 0xCB: ExecuteCBOpcode(ReadNextByte()); break;
            
            //------------------------     LOAD8     ------------------------//
            case 0x06: case 0x0E: case 0x16: case 0x1E:        //--- LD r,d8
            case 0x26: case 0x2E: case 0x36: case 0x3E:
                LD_r_d8(opcode); break;
            
            case >= 0x40 and <= 0x7F when opcode != 0x76:      //--- LD r,r'
                LD_r_r(opcode); break;
            
            case 0x02: case 0x12: LD_BCDE_A(opcode); break;    //--- LD (BC/DE),A
            case 0x0A: case 0x1A: LD_A_BCDE(opcode); break;    //--- LD A,(BC/DE)
            case 0x22: case 0x32: LD_HL_A(opcode);   break;    //--- LD (HL+/-),A
            case 0x2A: case 0x3A: LD_A_HL(opcode);   break;    //--- LD A,(HL+/-)
            
            case 0xE0: LDH_a8_A();  break;                      //--- LDH (a8),A
            case 0xF0: LDH_A_a8();  break;                      //--- LDH A,(a8)
            case 0xE2: LD_C_A();    break;                      //--- LD (C),A
            case 0xF2: LD_A_C();    break;                      //--- LD A,(C)
            case 0xEA: LD_a16_A();  break;                      //--- LD (a16),A
            case 0xFA: LD_A_a16();  break;                      //--- LD A,(a16)
            
            //------------------------    LOAD16     ------------------------//
            case 0x08: LD_a16_SP(); break;                      //--- LD (a16),SP
            case 0x01: case 0x11: case 0x21: case 0x31:         //--- LD rr,d16
                LD_rr_d16(opcode); break;
            
            //------------------------     ALU8     ------------------------//
            case 0x04: case 0x0C: case 0x14: case 0x1C:         //--- INC r/(HL)
            case 0x24: case 0x2C: case 0x34: case 0x3C:
                INC_r_HL(opcode); break;
            
            case 0x05: case 0x0D: case 0x15: case 0x1D:         //--- DEC r/(HL)
            case 0x25: case 0x2D: case 0x35: case 0x3D:
                DEC_r_HL(opcode); break;
            
            case 0x80: case 0x81: case 0x82: case 0x83:         //--- ADD A,r
            case 0x84: case 0x85: case 0x86: case 0x87:
                ADD_A_r(opcode); break;
            
            case 0x88: case 0x89: case 0x8A: case 0x8B:         //--- ADC A,r
            case 0x8C: case 0x8D: case 0x8E: case 0x8F:
                ADC_A_r(opcode); break;
            
            case 0xC6:                                          //--- ADD A,d8
            case 0xCE:                                          //--- ADC A,d8
                ADD_ADC_A_d8(opcode); break;
            
            case 0x90: case 0x91: case 0x92: case 0x93:         //--- SUB A,r
            case 0x94: case 0x95: case 0x96: case 0x97:
                SUB_A_r(opcode); break;
            
            case 0x98: case 0x99: case 0x9A: case 0x9B:         //--- SBC A,r
            case 0x9C: case 0x9D: case 0x9E: case 0x9F:
                SBC_A_r(opcode); break;
            
            case 0xD6:                                          //--- SBC A,d8
            case 0xDE:                                          //--- SBC A,d8
                SUB_SBC_A_d8(opcode); break;
            
            case 0xA0: case 0xA1: case 0xA2: case 0xA3:         //--- AND A,r
            case 0xA4: case 0xA5: case 0xA6: case 0xA7:
                AND_A_r(opcode); break;
            
            case 0xE6:                                          //--- AND A,d8
                AND_A_d8(); break;
            
            case 0xA8: case 0xA9: case 0xAA: case 0xAB:         //--- XOR A,r
            case 0xAC: case 0xAD: case 0xAE: case 0xAF:
                XOR_A_r(opcode); break;
            
            case 0xEE:                                          //--- XOR A,d8
                XOR_A_d8(); break;
            
            case 0xB0: case 0xB1: case 0xB2: case 0xB3:         //--- OR A,r
            case 0xB4: case 0xB5: case 0xB6: case 0xB7:
                OR_A_r(opcode); break;
            
            case 0xF6:                                          //--- OR A,d8
                OR_A_d8(); break;
            
            case 0xB8: case 0xB9: case 0xBA: case 0xBB:         //--- CP A,r
            case 0xBC: case 0xBD: case 0xBE: case 0xBF:
                CP_A_r(opcode); break;
            
            case 0xFE: CP_A_d8(); break;                        //--- CP A,d8
            case 0x27: DAA();     break;                        //--- DAA
            case 0x2F: CPL();     break;                        //--- CPL
            case 0x37: SCF();     break;                        //--- SCF
            case 0x3F: CCF();     break;                        //--- CCF
            
            //------------------------     ALU16     ------------------------//
            case 0x03: case 0x13: case 0x23: case 0x33:         //--- INC rr
                INC_rr(opcode); break;
            
            case 0x0B: case 0x1B: case 0x2B: case 0x3B:         //--- DEC rr
                DEC_rr(opcode); break;
            
            case 0x09: case 0x19: case 0x29: case 0x39:         //--- ADD HL,rr
                ADD_HL_rr(opcode); break;
            
            case 0xE8: ADD_SP_e8();  break;                     //--- ADD SP,e8
            case 0xF8: LD_HL_SPe8(); break;                     //--- LD HL,SP+e8
            case 0xF9: LD_SP_HL();   break;                     //--- LD SP,HL
            
            //------------------------    ROTATE    ------------------------//
            case 0x07: RCLA(); break;                           //--- RLCA (Rotate Left Circular Accumulator)
            case 0x0F: RRCA(); break;                           //--- RRCA (Rotate Right Circular Accumulator)
            case 0x17: RLA();  break;                           //--- RLA (Rotate Left through Accumulator)
            case 0x1F: RRA();  break;                           //--- RRA (Rotate Right through Accumulator)
            
            //------------------------     STACK    ------------------------//
            case 0xC1: case 0xD1: case 0xE1: case 0xF1:         //--- POP rr
                POP_rr(opcode); break;
            
            case 0xC5: case 0xD5: case 0xE5: case 0xF5:         //--- PUSH rr
                PUSH_rr(opcode); break;
            
            default: throw new NotSupportedException($"Opcode {opcode} not supported");
        }
        
        return (uint)(_state.CycleCount - cycleCountBeforeStep);
    }
    
    //--------------------------------------------------------------------------------------------------//
    //                                            HELPERS                                               //
    //--------------------------------------------------------------------------------------------------//
    /// <summary>
    /// Checks for pending enabled interrupts, waking HALT if needed and servicing one if IME is enabled.
    /// Returns true when this CPU step was consumed by interrupt handling.
    /// </summary>
    private bool HandleInterrupts()
    {
        byte pending = GetPendingInterrupts();
        
        if (pending == 0)   return false;       // No pending interrupts, continue.
        if (_state.Halted)  _state.Resume();    // HALT exits once an enabled interrupt is pending.
        if (_state.Stopped) return false;       // STOP wake remains simplified for now.
        
        if (!_state.InterruptMasterEnabled)
            return false;                       // Interrupt is pending, but IME still blocks servicing.

        ServiceInterrupt(pending);
        return true;
    }
    
    /// <summary>
    /// Services the highest-priority pending interrupt, clears its IF bit, disables IME, and jumps to its vector.
    /// </summary>
    private void ServiceInterrupt(byte pendingInterrupts)
    {
        if (_bus is null) return;

        byte   interruptMask;
        ushort vector;

        if ((pendingInterrupts & InterruptVBlank) != 0)
        {
            interruptMask = InterruptVBlank;
            vector = 0x0040;
        }
        else if ((pendingInterrupts & InterruptStat) != 0)
        {
            interruptMask = InterruptStat;
            vector = 0x0048;
        }
        else if ((pendingInterrupts & InterruptTimer) != 0)
        {
            interruptMask = InterruptTimer;
            vector = 0x0050;
        }
        else if ((pendingInterrupts & InterruptSerial) != 0)
        {
            interruptMask = InterruptSerial;
            vector = 0x0058;
        }
        else
        {
            interruptMask = InterruptJoypad;
            vector = 0x0060;
        }

        byte interruptFlags = _bus.ReadByte(InterruptFlagAddress);
        _bus.WriteByte(InterruptFlagAddress, (byte)(interruptFlags & ~interruptMask)); // Acknowledge chosen interrupt.

        _state.DisableInterrupts();   // Servicing an interrupt clears IME immediately.
        PushWord(_state.PC);          // Save current PC so RETI can resume execution.
        _state.PC = vector;           // Jump to interrupt handler vector.

        // Timing: 20 total cycles.
        // - interrupt entry behaves like a call to the vector.
        _state.AddClockCycles(MachineCycle * 5);
    }
    
    /// <summary> Computes IF & IE to determine which enabled interrupts are currently pending. </summary>
    private byte GetPendingInterrupts()
    {
        if (_bus is null) return 0;

        byte interruptFlags  = _bus.ReadByte(InterruptFlagAddress);
        byte interruptEnable = _bus.ReadByte(InterruptEnableAddress);
        return (byte)(interruptFlags & interruptEnable & 0x1F);
    }
    
    /// <summary> Reads the next word from the instruction stream; advances the PC. </summary>
    private byte ReadNextByte()
    {
        if (_bus is null) return 0;

        byte value = _bus.ReadByte(_state.PC);
        _state.PC++;

        return value;
    }

    /// <summary> Reads the next word from the instruction stream; advances the PC. </summary>
    private ushort ReadNextWord()
    {
        byte lo = ReadNextByte();
        byte hi = ReadNextByte();
        
        return (ushort)((hi << 8) | lo);
    }

    /// <summary> How HL should be adjusted after a memory access. </summary>
    private enum HLStep { None, Increment, Decrement }

    /// <summary> Read a byte from the address in HL, optionally adjusting HL after reading. </summary>
    private byte ReadAtHL(HLStep step = HLStep.None)
    {
        if (_bus is null) return 0;

        byte value = _bus.ReadByte(_state.HL);

        if (step == HLStep.Increment) _state.HL++;
        if (step == HLStep.Decrement) _state.HL--;
        
        return value;
    }
    
    /// <summary> Write a byte to the address in HL, optionally adjusting HL after writing. </summary>
    private void WriteAtHL(byte value, HLStep step = HLStep.None)
    {
        if (_bus is null) return;

        _bus.WriteByte(_state.HL, value);

        if (step == HLStep.Increment) _state.HL++;
        if (step == HLStep.Decrement) _state.HL--;
    }
    
    /// <summary> Read an 8-bit register by LR35902 register index (B,C,D,E,H,L,(HL),A). </summary>
    private byte ReadReg8(int reg)
    {
        return reg switch
        {
            0 => _state.B,
            1 => _state.C,
            2 => _state.D,
            3 => _state.E,
            4 => _state.H,
            5 => _state.L,
            6 => ReadAtHL(),
            7 => _state.A,
            _ => throw new ArgumentOutOfRangeException(nameof(reg), reg, "register index must be 0..7")
        };
    }
    
    /// <summary> Write an 8-bit register by LR35902 register index (B,C,D,E,H,L,(HL),A). </summary>
    private void WriteReg8(int reg, byte value)
    {
        switch (reg)
        {
            case 0: _state.B = value; break;
            case 1: _state.C = value; break;
            case 2: _state.D = value; break;
            case 3: _state.E = value; break;
            case 4: _state.H = value; break;
            case 5: _state.L = value; break;
            case 6: WriteAtHL(value); break;
            case 7: _state.A = value; break;
            default:
                throw new ArgumentOutOfRangeException(nameof(reg), reg, "register index must be 0..7");
        }
    }
    
    /// <summary> Set CPU flags in Z/N/H/C order. </summary>
    private void SetFlagsZNHC(bool z, bool n, bool h, bool c)
    {
        _state.SetFlags(z, n, h, c);
    }
    
    /// <summary>
    /// Adds signed 8-bit immediate to SP and updates flags per LR35902 rules.
    /// Used by: ADD SP,e8 and LD HL,SP+e8.
    /// </summary>
    private ushort AddSignedToSP(byte e8)
    {
        ushort sp = _state.SP;
        int    signed = unchecked((sbyte)e8);
        ushort result = (ushort)(sp + signed);

        // GB rule: Z=0, N=0, H/C from low-byte addition using unsigned e8.
        bool h = ((sp & 0x0F) + (e8 & 0x0F)) > 0x0F;
        bool c = ((sp & 0xFF) + e8) > 0xFF;

        SetFlagsZNHC(z: false, n: false, h: h, c: c);
        return result;
    }
    
    /// <summary> Makes condition code usage clearer than raw ints </summary>
    private enum ConditionCode { NZ = 0, Z  = 1, NC = 2, C  = 3 }

    /// <summary> Applies any delayed EI effect after the current instruction completes, then returns. </summary>
    private void CompleteInstruction()
    {
        if (_interruptEnabledPendingStateSnapshot)
            _state.ApplyPendingInterruptEnable();
    }
    
    /// <summary> Get the attached bus, which must be present while executing opcodes. </summary>
    private Bus Bus => _bus ?? throw new InvalidOperationException("CPU bus is not attached.");
}
