using Emulation;

namespace GameBoy.CPU;

/// <summary>
/// This class is a value object representing the internal state of the CPU, which the operational functions
/// on the CPU use to determine which steps to execute and to store values for and generated by those execs.
/// </summary>
public sealed class LR35902State : ICPUState
{
    //--------------------------------------------------------------------------------------------------//
    //                                           COUNTERS                                               //
    //--------------------------------------------------------------------------------------------------//
    public ushort PC         { get; internal set; } = 0x0100;   // Program Counter; Entry point
    public ushort SP         { get; internal set; } = 0xFFFE;   // Stack Pointer;   Top of HRAM
    public ulong  CycleCount { get; internal set; } = 0;        // Clock cycles (T-Cycles)
    
    //--------------------------------------------------------------------------------------------------//
    //                                           EXECUTION                                              //
    //--------------------------------------------------------------------------------------------------//
    public bool   Halted                  { get; private set; } // Halts instruction exec until interrupt
    public bool   Stopped                 { get; private set; } // CPU is stopped until external event
    public bool   InterruptMasterEnabled  { get; private set; } // IME flag controlling maskable interrupt servicing.
    public bool   InterruptEnabledPending { get; private set; } // EI sets this first; IME becomes true after the following instruction.

    public void Halt()   { Halted = true;  Stopped = false; }
    public void Stop()   { Halted = false; Stopped = true;  }
    public void Resume() { Halted = false; Stopped = false; }

    //--------------------------------------------------------------------------------------------------//
    //                                           REGISTERS                                              //
    //--------------------------------------------------------------------------------------------------//
    // The nibbled for registers on the CPU.
    // Together they form pairs which can be read out as such, the pairs are [ AF , BC, DE, HL ]
    public byte   A  { get; internal set; } = 0;
    public byte   B  { get; internal set; } = 0;
    public byte   C  { get; internal set; } = 0;
    public byte   D  { get; internal set; } = 0;
    public byte   E  { get; internal set; } = 0;
    public byte   F  { get; internal set; } = 0xB0;   // Convention (bits 5,7 set)
    public byte   H  { get; internal set; } = 0;
    public byte   L  { get; internal set; } = 0;
    
    // which are represented here in their full pairs
    // AF is used for the Accumulator and Flags:
    public ushort AF
    {
        get => (ushort)((A << 8) | F);
        set
        {
            A = (byte)(value >> 8);
            F = (byte)(value & 0xF0);   // lower nibble is always 0 on DMG CPU
        }
    }

    // While the other 3 are used as either general-purpose 16-bit registers,
    // though can also be split into 2 8-bit registers as needed by the program.
    // BC & DE are often used for data movement and counters.
    public ushort BC
    {
        get => (ushort)((B << 8) | C);
        set
        {
            B = (byte)(value >> 8);
            C = (byte)(value);
        }
    }

    public ushort DE
    {
        get => (ushort)((D << 8) | E);
        set
        {
            D = (byte)(value >> 8);
            E = (byte)(value);
        }
    }

    // While the HL register is frequently used as a memory pointer.
    public ushort HL
    {
        get => (ushort)((H << 8) | L);
        set
        {
            H = (byte)(value >> 8);
            L = (byte)(value);
        }
    }
    
    //--------------------------------------------------------------------------------------------------//
    //                                            FLAGS                                                 //
    //--------------------------------------------------------------------------------------------------//
    // Set of flags that can be set by the CPU  | The bitmasks for those flags.
    public bool FlagZ => (F & FlagZMask) != 0;   private const byte FlagZMask = 0x80;
    public bool FlagN => (F & FlagNMask) != 0;   private const byte FlagNMask = 0x40;
    public bool FlagH => (F & FlagHMask) != 0;   private const byte FlagHMask = 0x20;
    public bool FlagC => (F & FlagCMask) != 0;   private const byte FlagCMask = 0x10;
    
    //--------------------------------------------------------------------------------------------------//
    //                                          OPERATIONS                                              //
    //--------------------------------------------------------------------------------------------------//
    public void AddClockCycles(uint cycles)
    {
        CycleCount += cycles;
    }
    
    public void DisableInterrupts()
    {
        InterruptMasterEnabled  = false;   // DI clears IME immediately.
        InterruptEnabledPending = false;   // Any pending delayed enable is cancelled.
    }

    public void EnableInterrupts()
    {
        InterruptMasterEnabled  = true;    // Used by RETI or any direct IME enable path.
        InterruptEnabledPending = false;   // No delayed enable remains once IME is active.
    }

    public void ScheduleInterruptEnable()
    {
        InterruptEnabledPending = true;    // EI does not set IME immediately on LR35902.
    }

    public void ApplyPendingInterruptEnable()
    {
        if (!InterruptEnabledPending)
            return;

        InterruptMasterEnabled  = true;    // Apply EI's delayed effect.
        InterruptEnabledPending = false;   // Clear the latch once consumed.
    }
    
    public void SetFlags(bool z, bool n, bool h, bool c)
    {
        F = 0x00;
        if (z) F |= FlagZMask;
        if (n) F |= FlagNMask;
        if (h) F |= FlagHMask;
        if (c) F |= FlagCMask;
    }
    
    public void SetFlagZ(bool set) => SetFlag(FlagZMask, set);
    public void SetFlagN(bool set) => SetFlag(FlagNMask, set);
    public void SetFlagH(bool set) => SetFlag(FlagHMask, set);
    public void SetFlagC(bool set) => SetFlag(FlagCMask, set);
    
    private void SetFlag(byte mask, bool set)
    {
        if (set) F |= mask;
        else     F &= (byte)~mask;

        F &= 0xF0;
    }
    
    /// <summary> Reset the CPU State, this is usually done when a ROM is loaded </summary>
    public void Reset()
    {
        CycleCount = 0; 
        Halted = Stopped = false;
        InterruptMasterEnabled  = false;
        InterruptEnabledPending = false;
        
        PC = 0x0100; SP = 0xFFFE;

        A = 0x00; F = 0xB0;
        B = 0x00; C = 0x00;
        D = 0x00; E = 0x00;
        H = 0x00; L = 0x00;
    }

}